name : Michael Flores (floresam)'s blog
brand : Michael Flores
description : A blog where I often share thoughts resuting from work in the technology field
keyword : 
url : http://floresam.github.io/blog/
email : floresam@us.ibm.com.com
twitter : floresam90
github : floresam
author : Michael Flores
analytics : UA-8418273-8
year : 2017
markdown : kramdown
exclude :
  - node_modules

theme: jekyll-theme-time-machine
